/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/7.5.1/samples
 */

repositories {
    mavenCentral()
}

object Versions {
    const val apacheCommons = "1.10"
}

plugins {
    id("java")
}

configure<JavaPluginExtension> {
    sourceCompatibility = JavaVersion.VERSION_17
}

dependencies {
    implementation("commons-codec:commons-codec:${Versions.apacheCommons}")
}

sourceSets {
    test {
        java {
            srcDir("src/java/test")
        }
    }
}
